#! /bin/sh
#
# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Usage:
#   ./dcwrapper ARG [...]
#
# This is a wrapper script for docker-compose.  It loads SECRETS_ENV_FILE to get
# the current values of all secrets into the the shell environment, then invokes
# docker-compose with whatever args are passed.

SECRETS_ENV_FILE="./container/secrets/secrets.env"

if [ \! -f "${SECRETS_ENV_FILE}" ] ; then
  echo "Before continuing you should create the file ${SECRETS_ENV_FILE}"
  exit -1
fi

. ${SECRETS_ENV_FILE}

exec docker-compose "$@"
