version: '3.3'
services:
  editor-db:
    image: postgres:11
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./tmp/editor-db:/var/lib/postgresql/data

  oauth-proxy:
    build:
      context: .
      dockerfile: Dockerfile-oauth-proxy
    entrypoint: ["/bin/sh", "/container/config/oauth-proxy/launch"]
    volumes:
      - ./container/tools:/container/tools
      - ./container/secrets:/container/secrets
      - ./container/config/oauth-proxy:/container/config/oauth-proxy
    ports:
      - "4180"

  cgimap:
    build:
      context: .
      dockerfile: Dockerfile-cgimap
    entrypoint: ["/bin/bash", "/container/config/cgimap/launch"]
    volumes:
      - ./container/tools:/container/tools
      - ./container/secrets:/container/secrets
      - ./container/config/cgimap:/container/config/cgimap
    ports:
      - "${CGIMAP_PORT}"
    depends_on:
      - editor-db

  editor:
    build:
      context: .
      dockerfile: Dockerfile-editor
    entrypoint: ["/bin/bash", "/container/config/editor/launch"]
    volumes:
      - ./container/tools:/container/tools
      - ./container/secrets:/container/secrets
      - ./container/config/editor:/container/config/editor
      - ./editor-website/app:/srv/editor-website/app
    ports:
      - "${EDITOR_PORT}"
    depends_on:
      - editor-db

  warper-db:
    image: mdillon/postgis
    volumes:
      - ./tmp/warper-db:/var/lib/postgresql/data

  redis:
    image: redis

  warper:
    build:
      context: .
      dockerfile: Dockerfile-warper
    entrypoint: ["/bin/bash", "/container/config/warper/launch"]
    volumes:
      - ./container/tools:/container/tools
      - ./container/secrets:/container/secrets
      - ./container/config/warper:/container/config/warper
      - ./warper:/app
    ports:
      - "${MAPWARPER_PORT}"
      - "${MAPWARPER_INTERNAL_PORT}"
    depends_on:
      - warper-db
      - redis

  fe:
    build:
      context: .
      dockerfile: Dockerfile-fe
    entrypoint: ["/bin/sh", "/container/config/fe/launch"]
    volumes:
      - ./container/tools:/container/tools
      - ./container/secrets:/container/secrets
      - ./container/config/fe:/container/config/fe
      - ./public:/srv/public
      - ./renderer:/srv/renderer
    ports:
      - "${HOST_PORT}:${FE_PORT}"
    depends_on:
      - oauth-proxy
      - editor
      - cgimap
      - warper

  noter-backend-db:
    image: postgres:12
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      restart: always
    volumes:
      - ./tmp/noter-db:/var/lib/postgresql/data

  noter-backend:
    build:
      context: .
      dockerfile: Dockerfile-noter-backend
    ports:
      - "3001:3001"
    volumes:
      - ./container/tools:/container/tools
      - ./container/secrets:/container/secrets
      - ./container/config/noter-backend:/container/config/noter-backend
      - ./noter-backend:/noter-backend
    entrypoint: ["/bin/bash", "/container/config/noter-backend/launch"]
    depends_on:
      - noter-backend-db

  noter-frontend:
    build:
      context: .
      dockerfile: Dockerfile-noter-frontend
    ports:
      - "8082:3000"
    volumes:
      - ./container/tools:/container/tools
      - ./container/secrets:/container/secrets
      - ./container/config/noter-frontend:/container/config/noter-frontend
      - ./noter-frontend/src:/app/src
    entrypoint: ["/bin/bash", "/container/config/noter-frontend/launch"]
