version: '3.3'
services:
  editor-db:
    image: postgres:11
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./tmp/editor-db:/var/lib/postgresql/data

  oauth-proxy:
    build:
      context: .
      dockerfile: Dockerfile-oauth-proxy
    entrypoint: ["/bin/sh", "/container/config/oauth-proxy/launch"]
    volumes:
      - ./container/tools:/container/tools
      - ./container/secrets:/container/secrets
      - ./container/config/oauth-proxy:/container/config/oauth-proxy
    ports:
      - "4180"

  cgimap:
    build:
      context: .
      dockerfile: Dockerfile-cgimap
    entrypoint: ["/bin/bash", "/container/config/cgimap/launch"]
    volumes:
      - ./container/tools:/container/tools
      - ./container/secrets:/container/secrets
      - ./container/config/cgimap:/container/config/cgimap
    ports:
      - "${CGIMAP_PORT}"
    depends_on:
      - editor-db

  editor:
    build:
      context: .
      dockerfile: Dockerfile-editor
    entrypoint: ["/bin/bash", "/container/config/editor/launch"]
    volumes:
      - ./container/tools:/container/tools
      - ./container/secrets:/container/secrets
      - ./container/config/editor:/container/config/editor
      - ./editor-website/app:/srv/editor-website/app
    ports:
      - "${EDITOR_PORT}"
    depends_on:
      - editor-db

  warper-db:
    image: mdillon/postgis
    volumes:
      - ./tmp/warper-db:/var/lib/postgresql/data

  redis:
    image: redis

  warper:
    build:
      context: .
      dockerfile: Dockerfile-warper
    entrypoint: ["/bin/bash", "/container/config/warper/launch"]
    volumes:
      - ./container/tools:/container/tools
      - ./container/secrets:/container/secrets
      - ./container/config/warper:/container/config/warper
      - ./warper:/app
    ports:
      - "${MAPWARPER_PORT}"
      - "${MAPWARPER_INTERNAL_PORT}"
    depends_on:
      - warper-db
      - redis

  fe:
    build:
      context: .
      dockerfile: Dockerfile-fe
    entrypoint: ["/bin/sh", "/container/config/fe/launch"]
    volumes:
      - ./container/tools:/container/tools
      - ./container/secrets:/container/secrets
      - ./container/config/fe:/container/config/fe
      - ./public:/srv/public
    ports:
      - "${HOST_PORT}:${FE_PORT}"
    depends_on:
      - oauth-proxy
      - editor
      - cgimap
      - warper

  noter-backend-db:
    image: postgres:12
    environment:
      POSTGRES_DB: noter-backend
      POSTGRES_USER: noter-backend
      POSTGRES_PASSWORD: noter-backend
      restart: always
    expose:
      - "5432"

  noter-backend:
    environment:
      DJANGO_SETTINGS_MODULE: noter_backend.dev_settings
      DATABASE_URL: 'postgres://noter-backend:noter-backend@noter-backend-db:5432'
      NOTER_DB_HOST: 'noter-backend-db'
      NOTER_GS_PROJECT_ID: ''
      # If NOTER_GS_MEDIA_BUCKET_NAME is empty, local disk will be used.
      # You may lose the data if the disk is not persistent!
      PROTECTED_MEDIA_URL:
      NOTER_GS_MEDIA_BUCKET_NAME: ''
      GOOGLE_APPLICATION_CREDENTIALS: '/etc/google_cloud.json'
    build:
      context: .
      dockerfile: Dockerfile-noter-backend
    ports:
      - "3001:3001"
    volumes:
      - ./noter-backend:/noter-backend
    entrypoint: /noter-backend/docker-compose-entrypoint.sh
    depends_on:
      - noter-backend-db

  noter-frontend:
    build:
      context: .
      dockerfile: Dockerfile-noter-frontend
    ports:
      - "8081:3000"
    volumes:
      - ./noter-frontend/src:/app/src
    entrypoint: ["serve", "-s", "/app/build", "-l", "3000"]
