# docker build -t editor:latest -f Dockerfile-editor .

FROM ruby:2.5-slim-stretch

RUN apt-get update -qq

# install phusion passenger (step #1 from https://www.phusionpassenger.com/library/install/nginx/install/oss/bionic/)
RUN apt-get install -y --no-install-recommends dirmngr gnupg
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7
RUN apt-get install -y --no-install-recommends apt-transport-https ca-certificates
RUN sh -c 'echo deb https://oss-binaries.phusionpassenger.com/apt/passenger stretch main > /etc/apt/sources.list.d/passenger.list'

RUN mkdir -p /usr/share/man/man1
RUN mkdir -p /usr/share/man/man7

RUN apt-get update -qq && apt-get install -y --no-install-recommends \
  logrotate imagemagick postgresql-client nodejs phantomjs build-essential \
  libpqxx-dev libmagickwand-dev libxml2-dev libxslt1-dev libsasl2-dev libffi-dev \
  libgd-dev libarchive-dev libbz2-dev nginx-full libnginx-mod-http-passenger \
  gettext-base

RUN mkdir -p /srv
RUN mkdir -p /srv/editor-website
COPY editor-website/Gemfile /srv/editor-website/Gemfile
COPY editor-website/Gemfile.lock /srv/editor-website/Gemfile.lock

ENV RAILS_ROOT /srv/editor-website

WORKDIR $RAILS_ROOT

RUN gem install bundler -v=1.17.3 
RUN gem install bundle
RUN gem update --system
RUN bundle update --bundler
RUN bundle install

WORKDIR /

RUN rm -rf /srv/editor-website

ARG BUILD_ENV=production

ENV SECRET_KEY_BASE dummytokenforbuild

COPY ./editor-website/ /srv/editor-website/

WORKDIR $RAILS_ROOT

RUN rm -f config/credentials.yml.enc
RUN EDITOR=touch bundle exec rails credentials:edit

ENTRYPOINT ["nginx", "-g", "daemon off;"]
