# docker build -t fe:latest -f Dockerfile-fe .

FROM ubuntu:18.04

RUN apt-get update -qq

RUN apt-get install -y logrotate nginx-full iputils-ping gettext-base

RUN mkdir -p /srv
RUN mkdir -p /srv

COPY ./public /srv/public

RUN chmod -R a+rx /srv

ENTRYPOINT ["nginx", "-g", "daemon off;"]
