# docker build -t editor:latest -f Dockerfile-editor .

FROM ubuntu:18.04

RUN apt-get update -qq

# install phusion passenger (step #1 from https://www.phusionpassenger.com/library/install/nginx/install/oss/bionic/)
RUN apt-get install -y dirmngr gnupg
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7
RUN apt-get install -y apt-transport-https ca-certificates
RUN sh -c 'echo deb https://oss-binaries.phusionpassenger.com/apt/passenger bionic main > /etc/apt/sources.list.d/passenger.list'

RUN apt-get update -qq

RUN apt-get install -y build-essential git  logrotate libxml2-dev libpqxx-dev libfcgi-dev libboost-dev libboost-regex-dev libboost-program-options-dev libboost-date-time-dev libboost-filesystem-dev libboost-system-dev libboost-locale-dev libmemcached-dev libcrypto++-dev ruby2.5 libruby2.5 ruby2.5-dev libmagickwand-dev libxml2-dev libxslt1-dev nodejs build-essential git-core phantomjs postgresql-client libsasl2-dev imagemagick libffi-dev libgd-dev libarchive-dev libbz2-dev vim emacs nginx-full libnginx-mod-http-passenger curl iputils-ping gettext-base

RUN mkdir -p /srv
RUN mkdir -p /srv/editor-website
COPY editor-website/Gemfile /srv/editor-website/Gemfile
COPY editor-website/Gemfile.lock /srv/editor-website/Gemfile.lock

ENV RAILS_ROOT /srv/editor-website

WORKDIR $RAILS_ROOT

RUN gem install bundler -v=1.17.3 
RUN gem install bundle
RUN gem update --system
RUN bundle update --bundler
RUN bundle install

WORKDIR /

RUN rm -rf /srv/editor-website

ARG BUILD_ENV=production

ENV SECRET_KEY_BASE dummytokenforbuild

COPY ./editor-website/ /srv/editor-website/

WORKDIR $RAILS_ROOT

RUN rm -f config/credentials.yml.enc
RUN EDITOR=touch bundle exec rails credentials:edit

ENTRYPOINT ["nginx", "-g", "daemon off;"]
