# docker build -t cgimap:latest -f Dockerfile-cgimap .

FROM ubuntu:18.04

RUN apt-get update -qq

RUN apt-get install -y build-essential git logrotate vim emacs curl iputils-ping automake libxml2-dev libpqxx-dev libmemcached-dev libboost-dev libboost-regex-dev libboost-program-options-dev libboost-date-time-dev libboost-filesystem-dev libboost-system-dev libboost-locale-dev libfcgi-dev libcrypto++-dev libtool gettext-base

RUN mkdir -p /srv/openstreetmap-cgimap

COPY ./openstreetmap-cgimap/ /srv/openstreetmap-cgimap/

WORKDIR /srv/openstreetmap-cgimap

RUN ./autogen.sh
RUN ./configure
RUN make -j 4

ENTRYPOINT ["tail", "-f", "/dev/null"]
