#!/bin/sh
#
# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# usage:
#   ./start maps   - starts up all maps apps
#   ./start reservoir  - starts up the Reservoir app
#   ./start all    - starts up all apps      (as of 8/11/20, this is same as 'maps')

arg=$1

if [ "$arg" = "" ] ; then
  arg="all"
fi


SECRETS_ENV_FILE="./container/secrets/secrets.env"

if [ \! -f "${SECRETS_ENV_FILE}" ] ; then
  echo "Before continuing you should create the file ${SECRETS_ENV_FILE}"
  exit -1
fi

. ${SECRETS_ENV_FILE}

enabled_services=""

if [ "${ENABLE_MAP}" != "" ] ; then
  enabled_services="${enabled_services} -f docker-compose-map.yml"
fi
if [ "${ENABLE_RESERVOIR}" != "" ] ; then
  enabled_services="${enabled_services} -f ./reservoir/docker-compose.yml"
fi

case $arg in
  maps|all)
    ./dcwrapper -f ./docker-compose.yml ${enabled_services} up --remove-orphans
    ;;
  reservoir)
    ./dcwrapper -f ./docker-compose.empty.yml -f ./reservoir/docker-compose.yml up --remove-orphans
    ;;
  *)
    echo "unrecognized arg: $arg"
    exit -1
    ;;
esac
