#!/bin/bash
#
# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# usage:
#   ./start maps   - starts up all maps apps
#   ./start h3dmr  - starts up the h3dmr app
#   ./start all    - starts up all apps      (as of 8/11/20, this is same as 'maps')

arg=$1

if [ "$arg" == "" ] ; then
  arg="maps"
fi

case $arg in
  maps)
    ./dcwrapper -f ./docker-compose.yml -f ./h3dmr/docker-compose.yml up --remove-orphans
    ;;
  h3dmr)
    ./dcwrapper -f ./docker-compose.empty.yml -f ./h3dmr/docker-compose.yml up --remove-orphans
    ;;
  all)
    ./dcwrapper -f ./docker-compose.yml -f ./h3dmr/docker-compose.yml up --remove-orphans
    ;;
  *)
    echo "unrecognized arg: $arg"
    exit -1
    ;;
esac
