#! /bin/bash
#
# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

./k8s/resecret

kubectl delete job editor-empty-and-reinitialize-db --ignore-not-found 
./k8s/kcreate ./k8s/editor-empty-and-reinitialize-db-job.yaml.in

kubectl delete job warper-empty-and-reinitialize-db --ignore-not-found 
./k8s/kcreate ./k8s/warper-empty-and-reinitialize-db-job.yaml.in
