#! /usr/bin/python
#
# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import sys

def sys(cmd):
  print("+ " + cmd)
  return os.system(cmd)

sys("find container -name '*~' -print | xargs /bin/rm -f")

# replicate tegola-config.toml,osm2pgsql.style from 'antique' repo to container/config/tegola
if os.path.exists("antique/vector/tegola-config.toml"):
  sys("cp antique/vector/tegola-config.toml container/config/tegola")
  sys("cp antique/vector/osm2pgsql.style container/config/tegola")

sys("kubectl delete configmap container-tools")
sys("kubectl create configmap container-tools --from-file=container/tools")
sys("kubectl delete secret container-secrets")
sys("kubectl create secret generic container-secrets --from-file=container/secrets")


for f in os.listdir("container/config"):
  if os.path.isdir(os.path.join("container/config", f)):
    sys("kubectl delete configmap container-config-%s" % f)
    sys("kubectl create configmap container-config-%s --from-file=container/config/%s" % (f,f))
