#! /bin/bash

/bin/bash /container/config/editor/create-configs
. /container/secrets/secrets.env

export RAILS_ENV=${EDITOR_RAILS_ENV}

cd /srv/editor-website

psql -h ${EDITOR_DB_HOST} -d editor_${RAILS_ENV} -U ${EDITOR_DB_USER} -c "drop database ${EDITOR_DB_NAME};"

/bin/bash /container/config/editor/db-initialize
